### ISSUE TITLE
Please Remove the gray "fog" by default or make it more transparent...

### ISSUE THREAD

**Issue by JelliBelli123** [Variety-Mods/Variety-Aquatic#10]
As the title says, it needs to be fixed.
The models are so cool! I love this mod, but the fog nearly obscures the water to where underwater game play is just unplayable, and it doesn't make sense either when you can see things in the water when you aren't submerged. 

I enjoy this mod and the models so much, but the water fog shader "fix in the config yourself" solution is not something everyone is going to know and will just turn people away. It would be much better if it was a subtle fog, and if in a specific biome the leviathans spawn in or when they are spawned in, rather than every water biome. 

As it is now it just makes underwater game play, and adding new fish, unplayable.

**Comment by ColinVaughn** [comment]
Most like the darker water, a vocal minority don't like it but it is a easy fix.

**Comment by ColinVaughn** [comment]
It only takes a second to disable and you don't even have to restart your game if you use modmenu.

**Comment by ColinVaughn** [comment]
You an also make it less blurry if you change the start closer to 0, and then change the end farther from 0.

**Comment by JelliBelli123** [comment]
> It only takes a second to disable and you don't even have to restart your game if you use modmenu.

Without mod menu, what setting are you talking about? I only see the config file with the list of stuff in it, but nothing about fog. At the bottom of the config it has  
 "waterToggle": true,
  "waterStartDeep": -100.0,
  "waterEndDeep": 65.0,
  "waterEndSwamp": 50.0
  
  But when I set  "waterToggle" to false, it doesn't do anything. I've saved it too but I still get the fog issue.

**Comment by ColinVaughn** [comment]
What version are you on

**Comment by JelliBelli123** [comment]
1.20.1 Fabric

**Comment by ColinVaughn** [comment]
I'll check to see if the config options are working when in about an hour

**Comment by JelliBelli123** [comment]
> 1.20.1 Fabric

I should also add currently Mod Menu is not updated atm

> I'll check to see if the config options are working when in about an hour

Thank you

**Comment by ColinVaughn** [comment]
Started work on this now, by default fog will be way more transparent, more blue, and the fog color is now configurable.
