### ISSUE TITLE
[BUG] Weird Fish spawning in absurd amount in sky/under floating island

### ISSUE THREAD

**Issue by whatamaniac** [Variety-Mods/Variety-Aquatic#11]
**Describe the bug**
So i'm working on a modpack and while testing on server i found a fish dropping from the sky.. so i went above looking what spawned it. I found a Cursed Island from The Graveyard Mod and there were lots of fish spawning under it in air and on it. Within 4-5 mins there were thousands of fishes in ocean under the island + on the island.

**To Reproduce**
1. Generate a New World
2. Locate Cursed Island from The Graveyard mod 

**Expected behavior**
This is really weird bug and i've never seen anything like this so i did not expect anything.

**Screenshots**
I've recorded it. Here's the recording: https://www.veed.io/view/34ff0f81-7dae-40ba-b714-58740092777d?panel=share

**Desktop (please complete the following information):**
 - OS: Windows 11
- Modding Platfrom: Fabric 
 - Version: 0.14.21
- Minecraft Version: 1.19.2
- Modlist: https://pastebin.com/9VAy3v81

**Comment by ColinVaughn** [comment]
A fish has a screwed-up spawn restrictor

**Comment by ColinVaughn** [comment]
I'll fix this bug this week.

**Comment by whatamaniac** [comment]
No worries =] for Once i thought this was a Special Feature.... Cursed Island and It Rains Fish xDD

**Comment by ColinVaughn** [comment]
fixed it on the 1.19.2 version
