### ISSUE TITLE
Was crash fix issue now Glowing Squid -- Colin Vaughn

### ISSUE THREAD

**Issue by Rogenar** [Variety-Mods/Variety-Aquatic#2]
Game crashes in version 1.0.4.6 of Variety_Aquatic-fabric.
[crash-2023-06-11_20.50.53-client.txt](https://github.com/ColinVaughn/Variety-Aquatic/files/11715351/crash-2023-06-11_20.50.53-client.txt)
[rei.log](https://github.com/ColinVaughn/Variety-Aquatic/files/11715352/rei.log)
[rei-issues.log](https://github.com/ColinVaughn/Variety-Aquatic/files/11715353/rei-issues.log)
[latest.log](https://github.com/ColinVaughn/Variety-Aquatic/files/11715354/latest.log)

**Comment by ColinVaughn** [comment]
Looking into

**Comment by ColinVaughn** [comment]
Releasing a fix right now until I have time to fully fix this. The crash has been fixed but the animations are not being played for the beholder.

**Comment by Rogenar** [comment]
game crashes again

**Comment by ColinVaughn** [comment]
send new crash log, guess there were multiple crashes 😭

**Comment by ColinVaughn** [comment]
One crash I fixed was about illegal blockstate when placed.

**Comment by Rogenar** [comment]
[crash-2023-06-12_00.45.34-client.txt](https://github.com/ColinVaughn/Variety-Aquatic/files/11715792/crash-2023-06-12_00.45.34-client.txt)
[latest.log](https://github.com/ColinVaughn/Variety-Aquatic/files/11715793/latest.log)
[rei.log](https://github.com/ColinVaughn/Variety-Aquatic/files/11715794/rei.log)
[rei-issues.log](https://github.com/ColinVaughn/Variety-Aquatic/files/11715795/rei-issues.log)
The logs you want are here. now i have to go to bed i have to wake up at 06:30 so that i can go to work tomorrow morning
If the corrected version comes out when I get home from work, I'll try to get back to you.

**Comment by ColinVaughn** [comment]
I cannot replicate this crash at all when does it occur for you?

**Comment by ColinVaughn** [comment]
are you on linux/macos by chance?

**Comment by Rogenar** [comment]
I am using windows. My view on this situation is as follows. In 1.19.3 versions, this mode was working properly when there was no API requirement, but in 1.20 it worked normally in the first version, but in subsequent updates, a crash occurs.

**Comment by ColinVaughn** [comment]
test on the 1.20.1 version. It's really hard to fix this issue as it's not making a lot of sense because realistically this crash should happen for everyone but it only happens for you but I'm going to keep trying

**Comment by ColinVaughn** [comment]
The crash is basically saying the enum state that we use for our beholder block to handle the mode switching has an illegal character (which it doesn't) that is making your game crash.

**Comment by ColinVaughn** [comment]
Yeah the leviathan trophy isn't in officially so I didn't worry about fixing and ill look into the glow squid

**Comment by ColinVaughn** [comment]
The beholder animations and anemone model are fixed now, going to release the update today.

**Comment by Rogenar** [comment]
Ok then I'll be waiting for the updated version.

**Comment by ColinVaughn** [comment]
updated

**Comment by Rogenar** [comment]
now i was able to find time to try the updated version and in the latest version i faced the same visual error again. The giant glowing squid is constantly shaking.

**Comment by ColinVaughn** [comment]
Yeah, going to start working on figuring out that bug soon!

**Comment by ColinVaughn** [comment]
Focusing mainly on crash fixes, and compatibility then fixing other less major issues.

**Comment by Rogenar** [comment]
I turned off the water fog toggle setting and the problem went away.

**Comment by ColinVaughn** [comment]
Yeah it's not a problem it's a feature. Most like it but a lot have thalassophobia and just don't like it. It will probably be moved to a standalone addon with all scary features

**Comment by Rogenar** [comment]
I don't have thalassaphobia, but when I switch to instant blurred vision, it's hard to fight monsters underwater.

**Comment by ColinVaughn** [comment]
Yeah probably needs played around with. The start config option changes the vision blur, the end config changes the distance that you can see

**Comment by Rogenar** [comment]
As an underwater boss, do you plan to bring a big and powerful boss like a kraken or megalodon that drops rare beautiful items when killed?

**Comment by MysticKoko** [comment]
There's a variety of planned bosses, the Giant Glowsquid and the Leviathan are two of them, but we aren't revealing any more bosses until we have them fully fleshed out
