### ISSUE TITLE
Wheres all the blocks items and spawn eggs?

### ISSUE THREAD

**Issue by GittyGrittySocks** [Variety-Mods/Variety-Aquatic#6]
I can't find any mod related item in the creative menu

**Comment by ColinVaughn** [comment]
can you tell the version that you play on.

**Comment by GittyGrittySocks** [comment]
1.0.4.2

**Comment by ColinVaughn** [comment]
1.0.4.2 is an oudated version, if you are on 1.18.2/1.19.2/1.19.4/1.20/1.20.1 update.

If you are on forge or one of the depreciated versions the eggs for variety aquatic are on the same creative menu as vanilla spawn eggs.

**Comment by GittyGrittySocks** [comment]
So fabric is just outdated :|

**Comment by ColinVaughn** [comment]
if you are playing on any of the versions I didn't state then yes update to 1.18.2/1.19.2/1.19.4/1.20/1.20.1

**Comment by GittyGrittySocks** [comment]
Wait but I am on 1.20
I’m on the latest version which is 1.20/1.20.1 mod version 1.0.4.2

**Comment by ColinVaughn** [comment]
https://www.curseforge.com/minecraft/mc-mods/variety-aquatic/files/4586998 it's 1.0.4.7?

**Comment by GittyGrittySocks** [comment]
that's weird... Oh maybe on Modrinth it's 1.0.4.2 I'll try that one and see if it's better

**Comment by GittyGrittySocks** [comment]
It's working thanks :)

**Comment by ColinVaughn** [comment]
Updated modrinth
