### ISSUE TITLE
beholder crash

### ISSUE THREAD

**Issue by Promethesis** [Variety-Mods/Variety-Aquatic#9]
hi mate, still me ! im opening another topic beausee i think this should have is own

so, im having trouble with the beholder thing, here the crash report:

[crash-2023-06-18_22.47.40-client.txt](https://github.com/Variety-Mods/Variety-Aquatic/files/11785083/crash-2023-06-18_22.47.40-client.txt)

simply put, if i try right clicking with the beholder, the game freezes for like what, five sec, then it crashes. hope you can figure it out mate! And have a nice day to !

**Comment by ColinVaughn** [comment]
Hmm, I've seen this bug before but I thought I had fixed it. I will try to recreate this when I have a chance.

**Comment by ColinVaughn** [comment]
This has been fixed, releasing it on cf/modrinth rn.
